<?php

namespace App\DataFixtures;

use App\Entity\MediaObject;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;


class MediaObjectFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $imageUrls = [
            'acteurs/alban_ivanov.webp',
            'acteurs/brad_pitt.webp',
            'acteurs/bruce_willis.webp',
            'acteurs/christian_clavier.webp',
            'acteurs/didier_bourdon.webp',
            'acteurs/elodie_fontan.webp',
            'acteurs/eric_judor.webp',
            'acteurs/george_clooney.webp',
            'acteurs/gerard_depardieu.webp',
            'acteurs/gerard_jugnot.webp',
            'acteurs/gilles_lellouche.webp',
            'acteurs/jean_claude_van_damme.webp',
            'acteurs/jean_dujardin.webp',
            'acteurs/johnny_depp.webp',
            'acteurs/jonathan_cohen.webp',
            'acteurs/leonardo_dicaprio.webp',
            'acteurs/manu_payet.webp',
            'acteurs/omar_sy.webp',
            'acteurs/philippe_lacheau.webp',
            'acteurs/ramzy_bedia.webp',
            'acteurs/tarek_boudali.webp',
            'acteurs/taylor_swift.webp',
            'acteurs/tom_hanks.webp',
            'acteurs/will_smith.webp',
            'miniatures/les-simpson.jpeg',
            'miniatures/greys-anatomy.jpeg',
            'miniatures/desperate-housewives.jpeg',
            'miniatures/malcolm.jpeg',
            'miniatures/bluey.jpeg',
            'miniatures/modern-family.jpeg',
            'miniatures/loki.jpeg',
            'miniatures/esprits-criminels.jpeg',
            'miniatures/american-dad-!.jpeg',
            'miniatures/ma-famille-dabord.jpeg',
            'miniatures/how-i-met-your-mother.jpeg',
            'miniatures/ahsoka.jpeg',
            'miniatures/futurama.jpeg',
            'miniatures/les-griffin.jpeg',
            'miniatures/prison-break.jpeg',
            'miniatures/black-cake.jpeg',
            'miniatures/percy-jackson.jpeg',
            'miniatures/atlanta.jpeg',
            'miniatures/suncoast.jpeg',
            'miniatures/cristobal.jpeg',
            'miniatures/periple-dun-heros.jpeg',
            'miniatures/solar-opposites.jpeg',
            'miniatures/911.jpeg',
            'miniatures/encanto.jpeg',
            'miniatures/les-indestructibles.jpeg',
            'miniatures/buzz-leclair.jpeg',
            'miniatures/la-reine-des-neiges.jpeg',
            'miniatures/le-monde-de-dory.jpeg',
            'miniatures/rebelle.jpeg',
            'miniatures/vice-versa.jpeg',
            'miniatures/aladdin.jpeg',
            'background/les-simpson.jpeg',
            'background/greys-anatomy.jpeg',
            'background/desperate-housewives.jpeg',
            'background/malcolm.jpeg',
            'background/bluey.jpeg',
            'background/modern-family.jpeg',
            'background/loki.jpeg',
            'background/esprits-criminels.jpeg',
            'background/american-dad-!.jpeg',
            'background/ma-famille-dabord.jpeg',
            'background/how-i-met-your-mother.jpeg',
            'background/ahsoka.jpeg',
            'background/futurama.jpeg',
            'background/les-griffin.jpeg',
            'background/prison-break.jpeg',
            'background/black-cake.jpeg',
            'background/percy-jackson.jpeg',
            'background/atlanta.jpeg',
            'background/suncoast.jpeg',
            'background/cristobal.jpeg',
            'background/periple-dun-heros.jpeg',
            'background/solar-opposites.jpeg',
            'background/911.jpeg',
            'background/encanto.jpeg',
            'background/les-indestructibles.jpeg',
            'background/buzz-leclair.jpeg',
            'background/la-reine-des-neiges.jpeg',
            'background/le-monde-de-dory.jpeg',
            'background/rebelle.jpeg',
            'background/vice-versa.jpeg',
            'background/aladdin.jpeg',
            'logo/les-simpson.png',
            'logo/greys-anatomy.png',
            'logo/desperate-housewives.png',
            'logo/malcolm.png',
            'logo/bluey.png',
            'logo/modern-family.png',
            'logo/loki.png',
            'logo/esprits-criminels.png',
            'logo/american-dad-!.png',
            'logo/ma-famille-dabord.png',
            'logo/how-i-met-your-mother.png',
            'logo/ahsoka.png',
            'logo/futurama.png',
            'logo/les-griffin.png',
            'logo/prison-break.png',
            'logo/black-cake.png',
            'logo/percy-jackson.png',
            'logo/atlanta.png',
            'logo/suncoast.png',
            'logo/cristobal.png',
            'logo/periple-dun-heros.png',
            'logo/solar-opposites.png',
            'logo/911.png',
            'logo/encanto.png',
            'logo/les-indestructibles.png',
            'logo/buzz-leclair.png',
            'logo/la-reine-des-neiges.png',
            'logo/le-monde-de-dory.png',
            'logo/rebelle.png',
            'logo/vice-versa.png',
            'logo/aladdin.png',
        ];

        foreach (range(1, 117) as $i) {
            $mediaObject = new MediaObject();
            $mediaObject->setFilePath($imageUrls[$i - 1]);
            $manager->persist($mediaObject);
            $this->addReference('mediaObject_' . $i, $mediaObject);
        }

        $manager->flush();
    }
}