name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Deploy projet Symfony
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd public_html/travaux/wra506/
          rm -R dev_back-WRA506D
          git clone git@github.com:benjamin-frenal/dev_back-WRA506D.git
          cd dev_back-WRA506D
          git pull
          composer install
          php bin/console c:c
          composer require symfony/security-bundle
          composer require lexik/jwt-authentication-bundle
          php bin/console lexik:jwt:generate-keypair
          composer require --dev symfony/maker-bundle
          composer require --dev orm-fixtures
          composer require api
          php bin/console d:s:u --force
          php bin/console doctrine:fixtures:load
