name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Demo LS on VPS
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd public_html/travaux/wra506/
          git clone git@github.com:benjamin-frenal/dev_back-WRA506D.git
          cd dev_back-WRA506D
          git pull
          composer install
          php bin/console c:c
